export const initialCartItems = [
  {
    id: 1,
    image: "/products/product-2.png",
    badge: "day",
    inStock: true,
    rating: 4,
    name: "Velson film-coated tablets, 3mg, 30 ct",
    brand: "Lirina",
    packQty: "10 pcs",
    code: "153249",
    price: 41108,
    oldPrice: 49999,
    qty: 1,
  },
  {
    id: 2,
    image: "/products/product-4.png",
    badge: null,
    inStock: true,
    rating: 4,
    name: "Velson film-coated tablets, 3mg, 30 ct",
    brand: "Lirina",
    packQty: "10 pcs",
    code: "153249",
    price: 41108,
    oldPrice: 49999,
    qty: 1,
  },
  {
    id: 3,
    image: "/products/product-1.png",
    badge: null,
    inStock: true,
    rating: 4,
    name: "Velson film-coated tablets, 3mg, 30 ct",
    brand: "Lirina",
    packQty: "10 pcs",
    code: "153249",
    price: 41108,
    oldPrice: 49999,
    qty: 1,
  },
  {
    id: 4,
    image: "/products/product-5.png",
    badge: null,
    inStock: true,
    rating: 4,
    name: "Velson film-coated tablets, 3mg, 30 ct",
    brand: "Lirina",
    packQty: "10 pcs",
    code: "153249",
    price: 41108,
    oldPrice: 49999,
    qty: 1,
  },
];
